/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author salva
 */
public class Institucion extends javax.swing.JFrame {

    /**
     * Creates new form Institucion
     */
    public Institucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiFormularioDeMaterias = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiFormularioDeAlumnos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiManejoDeInscripciones = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiManipulacionDeNotas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiListadoDeAlumnosporMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Materias");

        jmiFormularioDeMaterias.setText("Formulario de materias");
        jmiFormularioDeMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioDeMateriasActionPerformed(evt);
            }
        });
        jMenu3.add(jmiFormularioDeMaterias);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Alumnos");

        jmiFormularioDeAlumnos.setText("Formulario de alumnos");
        jmiFormularioDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioDeAlumnosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFormularioDeAlumnos);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Inscripciones");

        jmiManejoDeInscripciones.setText("Manejo de inscripciones");
        jmiManejoDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManejoDeInscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(jmiManejoDeInscripciones);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Carga De Notas");

        jmiManipulacionDeNotas.setText("Manipulación de notas");
        jmiManipulacionDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManipulacionDeNotasActionPerformed(evt);
            }
        });
        jMenu5.add(jmiManipulacionDeNotas);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Consultas");

        jmiListadoDeAlumnosporMateria.setText("Listado de Alumnos por Materia");
        jmiListadoDeAlumnosporMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListadoDeAlumnosporMateriaActionPerformed(evt);
            }
        });
        jMenu6.add(jmiListadoDeAlumnosporMateria);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormularioDeMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioDeMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewMaterias vm = new ViewMaterias();
        vm.setVisible(true);
        escritorio.add(vm);
        escritorio.moveToFront(vm);
    }//GEN-LAST:event_jmiFormularioDeMateriasActionPerformed

    private void jmiFormularioDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioDeAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewAlumnos va = new ViewAlumnos();
        va.setVisible(true);
        escritorio.add(va);
        escritorio.moveToFront(va);
    }//GEN-LAST:event_jmiFormularioDeAlumnosActionPerformed

    private void jmiManejoDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManejoDeInscripcionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewFormularioInscripcion vfi = new ViewFormularioInscripcion();
        vfi.setVisible(true);
        escritorio.add(vfi);
        escritorio.moveToFront(vfi);
    }//GEN-LAST:event_jmiManejoDeInscripcionesActionPerformed

    private void jmiManipulacionDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManipulacionDeNotasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewCargaDeNotas vcn = new ViewCargaDeNotas();
        vcn.setVisible(true);
        escritorio.add(vcn);
        escritorio.moveToFront(vcn);
    }//GEN-LAST:event_jmiManipulacionDeNotasActionPerformed

    private void jmiListadoDeAlumnosporMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListadoDeAlumnosporMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ViewListadoDeAlumnosPorMateria vlapm = new ViewListadoDeAlumnosPorMateria();
        vlapm.setVisible(true);
        escritorio.add(vlapm);
        escritorio.moveToFront(vlapm);
    }//GEN-LAST:event_jmiListadoDeAlumnosporMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Institucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Institucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiFormularioDeAlumnos;
    private javax.swing.JMenuItem jmiFormularioDeMaterias;
    private javax.swing.JMenuItem jmiListadoDeAlumnosporMateria;
    private javax.swing.JMenuItem jmiManejoDeInscripciones;
    private javax.swing.JMenuItem jmiManipulacionDeNotas;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
